{%- if pillar.keystone.server is defined and pillar.keystone.server.get('enabled') %}
{% raw %}
server:
  alert:
    KeystoneAPIDown:
      if: >-
        max(openstack_api_check_status{service=~"keystone.+"}) by (service) == 0
      for: 2m
      labels:
        severity: down
        service: "{{ $labels.service }}"
      annotations:
        summary: "Endpoint check for '{{ $labels.service}}' is down"
        description: >-
            Endpoint check for '{{ $labels.service}}' is down for 2 minutes
{% endraw %}
{%- endif %}

